"""Seed archival document collections for demo data.

Run order:
1) python -m scripts.dev_seed_categories
2) python -m scripts.dev_seed_journals
3) python -m scripts.dev_seed_archives
4) python -m scripts.dev_seed_sites
5) python -m scripts.dev_seed_research_themes
6) python -m scripts.dev_seed_publications

Quick verification:
curl "http://127.0.0.1:8010/v1/categories?parent=archives"
curl "http://127.0.0.1:8010/v1/search/documents?category_slug=municipal-ledgers"
"""

from __future__ import annotations

from dataclasses import dataclass

from sqlalchemy import select
from sqlalchemy.orm import configure_mappers

from app.db.session import SessionLocal
from app.models import Category, CategoryKind, Document, DocumentType

configure_mappers()


@dataclass(frozen=True)
class DocumentSeed:
    title: str
    abstract: str
    lang: str
    year: int
    doc_type: DocumentType
    primary_category_slug: str
    pages: int | None = None
    doi: str | None = None
    isbn: str | None = None
    issn: str | None = None


CATEGORY_DEFAULTS: dict[str, tuple[str, CategoryKind, str, str | None]] = {
    "archives": (
        "Archives & Documentary Heritage",
        CategoryKind.section,
        "Finding aids, inventories, and digitized fonds drawn from manuscript, epistolary, and administrative archives.",
        None,
    ),
    "manuscript": (
        "Guide to Manuscript Collections",
        CategoryKind.archive_collection,
        "Catalogues, codicological notes, and access guides for manuscript libraries across Morocco.",
        "archives",
    ),
    "protectorate-records": (
        "Protectorate Records",
        CategoryKind.archive_collection,
        "Correspondence, bulletins, and dossiers generated by colonial administrations and protectorate offices.",
        "archives",
    ),
    "municipal-ledgers": (
        "Municipal Ledgers",
        CategoryKind.archive_collection,
        "Urban council proceedings, tax rolls, and civic accounting ledgers documenting municipal life.",
        "archives",
    ),
}


ARCHIVE_SEEDS: tuple[DocumentSeed, ...] = (
    DocumentSeed(
        title="Inventory of Qarawiyyin Manuscript Endowments (1890-1910)",
        abstract=(
            "This annotated inventory collates the waqf registers maintained for Qarawiyyin manuscript holdings between 1890 and 1910. "
            "It maps custodianship chains, marginalia, and conservation notes kept by the library staff. "
            "The dossier also includes a bilingual glossary of key terms used in the Arabic catalogue."
        ),
        lang="fr",
        year=1987,
        doc_type=DocumentType.archive_item,
        primary_category_slug="manuscript",
        pages=212,
    ),
    DocumentSeed(
        title="دليل مخطوطات آل بن جلون",
        abstract=(
            "يقدم هذا الدليل وصفاً تحليلياً للمخطوطات العائلية المحفوظة في مكتبة آل بن جلون في فاس. "
            "يتضمن تواريخ الملكية، وبيانات النسخ، وملاحظات عن حالة الورق والحبر. "
            "كما أضيفت فهارس مفصلة للأختام والتعاليق الهامشية."
        ),
        lang="ar",
        year=1994,
        doc_type=DocumentType.archive_item,
        primary_category_slug="manuscript",
        pages=168,
    ),
    DocumentSeed(
        title="Protectorate Bureau Correspondence on Marrakech Water Works (1912-1917)",
        abstract=(
            "A curated selection of administrative letters and engineering reports produced by the Protectorate's hydraulic bureau in Marrakech. "
            "The file documents negotiations with guilds and zawiyas over access to khettara channels. "
            "It concludes with a 1917 memorandum assessing the social impact of new pumping stations."
        ),
        lang="en",
        year=1933,
        doc_type=DocumentType.archive_item,
        primary_category_slug="protectorate-records",
        pages=94,
    ),
    DocumentSeed(
        title="Rapport sur les dossiers du Contrôle Civil de Casablanca",
        abstract=(
            "Ce rapport décrit l'état et la structure des dossiers produits par le Contrôle Civil de Casablanca durant l'entre-deux-guerres. "
            "Il recense les versements concernant l'urbanisme, la santé publique et la police municipale. "
            "Une section finale évalue les besoins de conservation pour les registres les plus fragiles."
        ),
        lang="fr",
        year=1956,
        doc_type=DocumentType.archive_item,
        primary_category_slug="protectorate-records",
        pages=131,
    ),
    DocumentSeed(
        title="Municipal Council Ledger of Fez, Fiscal Years 1924-1926",
        abstract=(
            "This ledger reproduces the deliberations of the Fez municipal council across three fiscal years. "
            "Budgets for sanitation, street lighting, and artisan guild regulation are presented with voting tallies. "
            "An appended English commentary situates the reforms within wider regional governance shifts."
        ),
        lang="en",
        year=1927,
        doc_type=DocumentType.archive_item,
        primary_category_slug="municipal-ledgers",
        pages=286,
    ),
    DocumentSeed(
        title="Registre arabe des amendes municipales de Rabat (1931-1933)",
        abstract=(
            "Ce registre manuscrit consigne, en arabe، الرسوم والغرامات المفروضة على أصحاب الحرف في الرباط بين 1931 و1933. "
            "Il distingue les infractions selon les quartiers et renseigne sur les montants perçus chaque mois. "
            "Des annotations en marge signalent les cas de remise exceptionnelle décidés par الباشا."
        ),
        lang="ar",
        year=1934,
        doc_type=DocumentType.archive_item,
        primary_category_slug="municipal-ledgers",
    ),
    DocumentSeed(
        title="دفاتر جباية مدينة تطوان (1915-1918)",
        abstract=(
            "توثق هذه الدفاتر سجلات القباضات البلدية بتطوان خلال سنوات الحرب العالمية الأولى. "
            "تُظهر البيانات نسب العائدات وتذبذب الرسوم في ظل اضطراب التجارة عبر البحر المتوسط. "
            "يُختتم الملف لمحة تحليلية حول أثر الضرائب على الحرفيين والباعة المتنقلين."
        ),
        lang="ar",
        year=1919,
        doc_type=DocumentType.archive_item,
        primary_category_slug="municipal-ledgers",
        pages=176,
    ),
)


def get_category_by_slug(session, slug: str) -> Category | None:
    return session.execute(select(Category).where(Category.slug == slug)).scalar_one_or_none()


def ensure_category(
    session,
    *,
    slug: str,
    name: str,
    kind: CategoryKind,
    description: str,
    parent: Category | None = None,
) -> tuple[Category, bool, bool]:
    category = get_category_by_slug(session, slug)
    if category is None:
        category = Category(
            slug=slug,
            name=name,
            kind=kind,
            description=description,
            parent=parent,
        )
        session.add(category)
        session.flush()
        return category, True, False

    updated = False
    if category.name != name:
        category.name = name
        updated = True
    if category.kind != kind:
        category.kind = kind
        updated = True
    if category.description != description:
        category.description = description
        updated = True
    if parent is None:
        if category.parent_id is not None:
            category.parent = None
            updated = True
    else:
        if category.parent_id != parent.id:
            category.parent = parent
            updated = True
    return category, False, updated


def ensure_required_categories(session) -> dict[str, Category]:
    resolved: dict[str, Category] = {}
    parents: dict[str, Category | None] = {}
    for slug, (name, kind, description, parent_slug) in CATEGORY_DEFAULTS.items():
        if parent_slug:
            parent = resolved.get(parent_slug)
            if parent is None:
                parent = get_category_by_slug(session, parent_slug)
                if parent is None:
                    parent_name, parent_kind, parent_desc, _ = CATEGORY_DEFAULTS[parent_slug]
                    parent, _, _ = ensure_category(
                        session,
                        slug=parent_slug,
                        name=parent_name,
                        kind=parent_kind,
                        description=parent_desc,
                        parent=None,
                    )
                resolved[parent_slug] = parent
            parents[slug] = parent
        else:
            parents[slug] = None

    for slug, (name, kind, description, parent_slug) in CATEGORY_DEFAULTS.items():
        parent = parents[slug]
        category, _, _ = ensure_category(
            session,
            slug=slug,
            name=name,
            kind=kind,
            description=description,
            parent=parent,
        )
        resolved[slug] = category
    return resolved


def upsert_document(session, seed: DocumentSeed, categories: dict[str, Category]) -> tuple[bool, bool]:
    document = session.execute(select(Document).where(Document.title == seed.title)).scalar_one_or_none()
    created = False
    updated = False
    primary_category = categories[seed.primary_category_slug]

    def maybe_set(obj: Document, attr: str, value):
        nonlocal updated
        if getattr(obj, attr) != value:
            setattr(obj, attr, value)
            updated = True

    if document is None:
        document = Document(
            title=seed.title,
            abstract=seed.abstract,
            lang=seed.lang,
            year=seed.year,
            type=seed.doc_type,
            pages=seed.pages,
            doi=seed.doi,
            isbn=seed.isbn,
            issn=seed.issn,
            primary_category=primary_category,
        )
        session.add(document)
        session.flush()
        created = True
        return created, updated

    maybe_set(document, "abstract", seed.abstract)
    maybe_set(document, "lang", seed.lang)
    maybe_set(document, "year", seed.year)
    if document.type != seed.doc_type:
        document.type = seed.doc_type
        updated = True
    maybe_set(document, "pages", seed.pages)
    maybe_set(document, "doi", seed.doi)
    maybe_set(document, "isbn", seed.isbn)
    maybe_set(document, "issn", seed.issn)
    if document.primary_category_id != primary_category.id:
        document.primary_category = primary_category
        updated = True
    return created, updated


def seed() -> None:
    session = SessionLocal()
    inserted = 0
    updated = 0
    per_collection: dict[str, int] = {"manuscript": 0, "protectorate-records": 0, "municipal-ledgers": 0}
    try:
        categories = ensure_required_categories(session)
        for seed_row in ARCHIVE_SEEDS:
            created, changed = upsert_document(session, seed_row, categories)
            per_collection[seed_row.primary_category_slug] += 1
            inserted += int(created)
            updated += int(changed and not created)

        session.commit()
        print(
            f"Archive items seeded — inserted: {inserted}, updated: {updated}, total: {len(ARCHIVE_SEEDS)}."
        )
        for slug, count in per_collection.items():
            print(f"  - {slug}: {count} document(s)")
    except Exception:
        session.rollback()
        raise
    finally:
        session.close()


if __name__ == "__main__":
    seed()
