"""Seed core navigation categories for the demo dataset.

Run order:
1) python -m scripts.dev_seed_categories
2) python -m scripts.dev_seed_journals
3) python -m scripts.dev_seed_archives
4) python -m scripts.dev_seed_sites
5) python -m scripts.dev_seed_research_themes
6) python -m scripts.dev_seed_publications

Quick verification:
curl "http://127.0.0.1:8010/v1/categories?kind=section"
curl "http://127.0.0.1:8010/v1/categories?parent=archives"
curl "http://127.0.0.1:8010/v1/categories?parent=research-themes"
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Sequence

from sqlalchemy import select
from sqlalchemy.orm import configure_mappers

from app.db.session import SessionLocal
from app.models import Category, CategoryKind

configure_mappers()  # ensure all mappers are configured before use


@dataclass(frozen=True)
class CategorySeed:
    slug: str
    name: str
    kind: CategoryKind
    description: str
    children: tuple["CategorySeed", ...] = field(default_factory=tuple)


SEED_TREE: tuple[CategorySeed, ...] = (
    CategorySeed(
        slug="library",
        name="Library Collections",
        kind=CategoryKind.section,
        description=(
            "Curated monographs, bibliographies, reading guides, and reference tools spanning Maghribi studies."
        ),
    ),
    CategorySeed(
        slug="journals",
        name="Journals",
        kind=CategoryKind.section,
        description="Serials and bulletins capturing peer-reviewed, grey, and community-based scholarship.",
    ),
    CategorySeed(
        slug="archives",
        name="Archives & Documentary Heritage",
        kind=CategoryKind.section,
        description=(
            "Finding aids, inventories, and digitized fonds drawn from manuscript, epistolary, and administrative archives."
        ),
        children=(
            CategorySeed(
                slug="manuscript",
                name="Guide to Manuscript Collections",
                kind=CategoryKind.archive_collection,
                description="Catalogues, codicological notes, and access guides for manuscript libraries across Morocco.",
            ),
            CategorySeed(
                slug="protectorate-records",
                name="Protectorate Records",
                kind=CategoryKind.archive_collection,
                description="Correspondence, bulletins, and dossiers generated by colonial administrations and protectorate offices.",
            ),
            CategorySeed(
                slug="municipal-ledgers",
                name="Municipal Ledgers",
                kind=CategoryKind.archive_collection,
                description="Urban council proceedings, tax rolls, and civic accounting ledgers documenting municipal life.",
            ),
        ),
    ),
    CategorySeed(
        slug="historical-sites",
        name="Historical Sites",
        kind=CategoryKind.section,
        description="Documentation of architectural ensembles, archaeological sites, and cultural landscapes.",
    ),
    CategorySeed(
        slug="research-themes",
        name="Research Themes",
        kind=CategoryKind.section,
        description="Cross-cutting scholarly conversations that link archives, fieldwork, and interpretive communities.",
        children=(
            CategorySeed(
                slug="urban-histories",
                name="Urban Histories",
                kind=CategoryKind.topic,
                description="Neighbourhoods, governance, and the rhythms of everyday urban life.",
            ),
            CategorySeed(
                slug="material-culture",
                name="Material Culture",
                kind=CategoryKind.topic,
                description="Objects, artisanship, and museum practices across the Maghrib.",
            ),
            CategorySeed(
                slug="intellectual-networks",
                name="Intellectual Networks",
                kind=CategoryKind.topic,
                description="Lineages, translation, and the circulation of knowledge across languages and regions.",
            ),
        ),
    ),
    CategorySeed(
        slug="publications",
        name="Publications",
        kind=CategoryKind.section,
        description="Foundation publications, working papers, translations, and policy briefs released for public use.",
    ),
)


def get_category_by_slug(session, slug: str) -> Category | None:
    return session.execute(select(Category).where(Category.slug == slug)).scalar_one_or_none()


def ensure_category(
    session,
    *,
    slug: str,
    name: str,
    kind: CategoryKind,
    description: str,
    parent: Category | None = None,
) -> tuple[Category, bool, bool]:
    category = get_category_by_slug(session, slug)
    if category is None:
        category = Category(
            slug=slug,
            name=name,
            kind=kind,
            description=description,
            parent=parent,
        )
        session.add(category)
        session.flush()
        return category, True, False

    updated = False
    if category.name != name:
        category.name = name
        updated = True
    if category.kind != kind:
        category.kind = kind
        updated = True
    if category.description != description:
        category.description = description
        updated = True
    if parent is None:
        if category.parent_id is not None:
            category.parent = None
            updated = True
    else:
        if category.parent_id != parent.id:
            category.parent = parent
            updated = True
    return category, False, updated


def seed_children(
    session,
    parent: Category,
    children: Sequence[CategorySeed],
    summary: list[tuple[str, str]],
    counters: dict[str, int],
) -> None:
    for child in children:
        node, created, updated = ensure_category(
            session,
            slug=child.slug,
            name=child.name,
            kind=child.kind,
            description=child.description,
            parent=parent,
        )
        counters["created"] += int(created)
        counters["updated"] += int(updated)
        summary.append((child.slug, "created" if created else ("updated" if updated else "ok")))
        if child.children:
            seed_children(session, node, child.children, summary, counters)


def seed() -> None:
    session = SessionLocal()
    created_updated_summary: list[tuple[str, str]] = []
    counters = {"created": 0, "updated": 0}
    try:
        for node in SEED_TREE:
            category, created, updated = ensure_category(
                session,
                slug=node.slug,
                name=node.name,
                kind=node.kind,
                description=node.description,
                parent=None,
            )
            counters["created"] += int(created)
            counters["updated"] += int(updated)
            created_updated_summary.append(
                (node.slug, "created" if created else ("updated" if updated else "ok"))
            )
            if node.children:
                seed_children(session, category, node.children, created_updated_summary, counters)

        session.commit()
        print(
            f"Categories ensured — created: {counters['created']}, updated: {counters['updated']}, total processed: {len(created_updated_summary)}."
        )
        for slug, status in created_updated_summary:
            print(f"  - {slug}: {status}")
    except Exception:
        session.rollback()
        raise
    finally:
        session.close()


if __name__ == "__main__":
    seed()
